version: "3.9"
services:
  web:
    build:
      context: ./nginx
    container_name: desafio_web
    entrypoint: dockerize --wait tcp://app:3000 --timeout 3600s /docker-entrypoint.sh
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - desafio-network
  app:
    build:
      context: ./nodejs
    container_name: desafio_app
    entrypoint: dockerize --wait tcp://db:3306 --timeout 20s docker-entrypoint.sh
    command: bash -c "npm install --silent; node index.js"
    volumes:
      - ./nodejs:/usr/src/app
    tty: true
    depends_on:
      - db
    networks:
      - desafio-network
  db:
    image: "mysql:5.7"
    command: "--innodb-use-native-aio=0"
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/entrypoint:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    networks:
      - desafio-network
networks:
  desafio-network:
    driver: bridge